global:
  scrape_interval: 10s # 10초마다 매트릭을 수집 default 1분
  evaluation_interval: 1m # 1분마다 규칙을 평가 default 1분


  external_labels: # 외부 시스템에 표시할 이 서버의 레이블
    monitor: 'messenger-monitor'

rule_files: # 규칙을 로딩하고 evaluation_interval 설정에 따라 정기적으로 평가한다.
# - "first.rules"
# - "second.rules"

# Here it's Prometheus itself. # 프로메테우스 자체에서 제공하는 메트릭 정보
scrape_configs:
  # 작업 이름은이 구성에서 스크랩되는 모든 시계열에 레이블 'job = <job_name>'을 추가합니다.
  - job_name: "prometheus"

    # metrics_path는 기본값 '/ metrics' 입니다.
    # scheme의 기본값은 'http'입니다.

    static_configs:
#      - targets: ["localhost:9090"]
      - targets: ["${{ secrets.URL }}:9090"] #배포 퍼블릭 IPv4 주소


  - job_name: "monitoring"
    metrics_path: '/actuator/prometheus'  # 메트릭을 수집할 path 설정
    scrape_interval: 5s
    static_configs:
#      - targets: ["host.docker.internal:8080"]   # Docker 컨테이너로 실행되는 애플리케이션에 대한 호스트 머신의 IP 주소
#      즉 docker 컨테이너 에 해당 애플리케이션을 포함시켰을때 사용
#      - targets: ["localhost:8080"] # 특정 컨테이너에서 실행 중인 애플리케이션을 호스트 머신
      - targets: ["${{ secrets.URL }}:8080"] #배포 퍼블릭 IPv4 주소
